export const TEST = 'TEST';
export const CHANGE_DIAGRAM = 'CHANGE_DIAGRAM';
export const GET_DIAGRAM_XML = 'GET_DIAGRAM_XML';
export const GET_INSTANCE_HISTORY = 'GET_INSTANCE_HISTORY';
export const GET_INSTANCE_INFO = 'GET_INSTANCE_INFO';
export const GET_INSTANCE_CHILDNODE = 'GET_INSTANCE_CHILDNODE';
export const CHOOSING_TASK = 'CHOOSING_TASK';